
# 错误处理

Rust将错误分为两种：
1. 可恢复性错误，即不会导致系统崩溃的错误，如用户操作错误
2. 不可恢复错误，该错误通常是全局性或者系统性的错误，会导致系统崩溃，例如数组越界访问

对于可恢复性错误，Rust使用`Result<T, E>`处理，对于不可恢复性错误，Rust使用`panic!`处理

## panic

### panic使用

```rust
fn main() {
    panic!("crash and burn");
}
```

有两种处理panic的方式：
- 栈展开：使用`RUST_BACKTRACE=1 cargo run`可以展开调用栈，最近调用的函数在最上面。为了开启栈展开，程序需要开启debug。
- 直接终止：如果担心debug模式程序太大，直接终止程序，可以如下配置
  ```rust
    [profile.release]
    panic = 'abort'
  ```

如果main进程panic，程序终止。如果子进程panic，子进程终止而主进程不会。

### expect与unwarp

- 如果返回值是OK，提取枚举中的值，如果返回值是Err，panic
- expect比unwarp多一个错误信息参数
- expect和unwarp也可以对Option使用

```rust
use std::net::IpAddr;
let home: IpAddr = "127.0.0.1".parse().unwrap();
let home: IpAddr = "127.0.0".parse().expect("格式错误"); // panic
let v = Some(1).unwrap();
let v :i32 = None.unwrap(); // panic
let v :i32 = None.expect("aaa"); // panic
```

### 何时使用panic

1. 确定程序没问题时，如`let home: IpAddr = "127.0.0.1".parse().unwrap();`，ip地址肯定没错
2. 示例、测试等需要快速搭建代码的场景
3. 可能导致更严重错误时，如后续代码功能受影响